---
title: "Assignment 4"
author: "Marco Palombo"
date: "5/18/2022"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(thematic)
library(scales)
library(equatiomatic)
```

```{r import data}
#import damages data set
damages <- read_csv(here("damages.csv")) %>% 
  #rename column damages because having it names the same thing as the dataset is super stupid
  mutate(harm = damages) %>% 
  select(-damages)

#import warming data set
warming <- read_csv(here("warming.csv"))

```

## Question 1
```{r question 1}
# first add a column to the dataset of damages squared because it seems lm wants that to do a quadratic fit
damages_fit <- damages %>% 
  mutate(warming2 = warming^2)

# perform fit
quad_fit <- lm(harm ~ warming + warming2 + 0, data = damages_fit)
summary(quad_fit)

quad_func <- function(warming){
  harm <- quad_fit$coefficients[1]*warming + quad_fit$coefficients[2]*warming^2
  return(harm)
}

# populate column of harm from fit function
damages_fit$harm_fit = quad_func(damages_fit$warming)

ggplot(data = damages_fit, aes(x = warming, y = harm))+
  geom_point(aes(x = warming, y = harm))+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  labs(x = "Warming (Degrees Celcius)", y = "Damages (figure out units)")
  
  
```

**Figure 1: Damages vs Warming. Points are from given dataset. Blue line is quadratic fit with zero intercept.**

## Question 2

```{r}
#populate columns of warming with damages for pulse, no pulse, difference between pulse and no pulse, difference in damage per ton co2
#pulse
warming$pulse_damage <- quad_func(warming$warming_pulse)
#nopulse
warming$nopulse_damage <- quad_func(warming$warming_baseline)
# difference
warming$dif <- warming$pulse_damage - warming$nopulse_damage

# unclear how to interpret the per ton CO2 comment for final column. Does this mean divide the whole column by 35? Or is there some sort of temporal component. Given it is referred to as a one time release today I will assume the 35 is in the air at the beginning of the dataset and will therefore simply divide the difference by 35
warming$dif_per_ton <- warming$dif/35e9

# now generate the plots
# no pulse
ggplot(data = warming)+
  geom_line(aes(x = year, y = nopulse_damage))+
  labs(title = "no pulse", x = "Calendar year", y = "Damages (unknown units)")

# pulse
ggplot(data = warming)+
  geom_line(aes(x = year, y = pulse_damage))+
  labs(title = "pulse", x = "Calendar year", y = "Damages (unknown units)")

# difference
ggplot(data = warming)+
  geom_line(aes(x = year, y = dif))+
  labs(title = "difference", x = "Calendar year", y = "Damages (unknown units)")

# difference per ton
ggplot(data = warming)+
  geom_line(aes(x = year, y = dif_per_ton))+
  labs(title = "difference per ton", x = "Calendar year", y = "Damages (unknown units)")
```

